/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KleeatAmbulanceWlList {
    }
}
declare global {
    interface HTMLKleeatAmbulanceWlListElement extends Components.KleeatAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLKleeatAmbulanceWlListElement: {
        prototype: HTMLKleeatAmbulanceWlListElement;
        new (): HTMLKleeatAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "kleeat-ambulance-wl-list": HTMLKleeatAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface KleeatAmbulanceWlList {
    }
    interface IntrinsicElements {
        "kleeat-ambulance-wl-list": KleeatAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kleeat-ambulance-wl-list": LocalJSX.IntrinsicElements["kleeat-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLKleeatAmbulanceWlListElement>;
        }
    }
}
